N.B: Please find the answers by applying the functions on the matrices

1. Create 2 3×3 matrix with 0-8 and 10-19 as elements in each and perform the vectorize multiplication operations on the matrices.(Outer product, Dot product, Element wise product).

In [ ]:
import numpy as np

a1 = np.arange(0,9).reshape(3,3)
a2  = np.arange(10,19).reshape(3,3)

out = np.outer(a1,a2)
print("Outer product: \n",out)

print("----------------------")

dot = np.dot(a1,a2)
print("Dot product: \n",dot)

print("----------------------")

mul = np.multiply(a1,a2)
print("Element wise product: \n",mul)


2. Create a 4×4 matrix with 0-16  as elements in it. Add a scalar 4 to the matrix and also multiply it with [1,2,3,4] 1-D matrix by broadcasting. ( Please note to do both the addition and multiplication by broadcasting.)

In [3]:
import numpy as np

a1 = np.arange(0,16).reshape(4,4)
a2 = np.array([1,2,3,4])
ad = a1+4
print(ad)

m = ad*a2
print(m)


[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 4 10 18 28]
 [ 8 18 30 44]
 [12 26 42 60]
 [16 34 54 76]]
