1. Create an 4x4 array with elements ranging from 0-15. And find the trace of the array.

In [2]:
import numpy as np

a1 = np.arange(0,16).reshape(4,4)
trace = a1.trace()
print(trace)

30


2. Create a matrix with elements [6,1,1],[4,-2,5],[2,8,7].Now find the inverse this matrix.

In [4]:
import numpy as np

a1 = np.matrix('[6,1,1;4,-2,5;2,6,7]')
print(np.linalg.inv(a1))

[[ 0.17322835  0.00393701 -0.02755906]
 [ 0.07086614 -0.15748031  0.1023622 ]
 [-0.11023622  0.13385827  0.06299213]]


3. Create an 3x3 array with elements ranging from 0-8. And find the norm this array.

In [5]:
import numpy as np

a1 = np.arange(0,9).reshape(3,3)
print(np.linalg.norm(a1))

14.2828568570857


4. Create a 4x4 array whose value ranging from 0-15.And find the eigenvalues and eigenvectors of this array.

In [7]:
import numpy as np

a1 = np.arange(0,16).reshape(4,4)
print(np.linalg.eig(a1))

(array([ 3.24642492e+01, -2.46424920e+00,  2.55670932e-15, -1.93389056e-16]), array([[-0.11417645,  0.7327781 , -0.54471271,  0.09683789],
       [-0.3300046 ,  0.28974835,  0.76902356,  0.27269982],
       [-0.54583275, -0.15328139,  0.09609099, -0.8359133 ],
       [-0.76166089, -0.59631113, -0.32040185,  0.46637559]]))
