1. Generate a 3 x 3 matrix using random module.

In [17]:
import random

a = []
b = [0,0,0]

for i in range(0, 3):
  for i in range(0,3):
    b[i] = random.randint(0,9)
  a.append(b)
print(a)

[[7, 0, 1], [7, 0, 1], [7, 0, 1]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [27]:
import numpy as np

a = np.random.rand(4,4)
print(a)

print("Vertical stack")
print(np.vstack(a))

print("Horizontal stack")
print(np.hstack(a))

[[0.95017229 0.72565429 0.05655204 0.41856662]
 [0.7415376  0.0563009  0.62279992 0.54066161]
 [0.117698   0.30888615 0.32040797 0.72340821]
 [0.87270579 0.3658066  0.56304773 0.1363237 ]]
Vertical stack
[[0.95017229 0.72565429 0.05655204 0.41856662]
 [0.7415376  0.0563009  0.62279992 0.54066161]
 [0.117698   0.30888615 0.32040797 0.72340821]
 [0.87270579 0.3658066  0.56304773 0.1363237 ]]
Horizontal stack
[0.95017229 0.72565429 0.05655204 0.41856662 0.7415376  0.0563009
 0.62279992 0.54066161 0.117698   0.30888615 0.32040797 0.72340821
 0.87270579 0.3658066  0.56304773 0.1363237 ]
