1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [3]:
import numpy as np

arr = np.arange(0,9).reshape(3,3)
print(arr)
print(f"sum: {np.sum(arr)}")

[[0 1 2]
 [3 4 5]
 [6 7 8]]
sum: 36


2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [16]:
import numpy as np

arr = np.arange(0,9).reshape(3,3)

print(f"sum of column: {np.sum(arr, axis=0)}")
print(f"sum of row: {np.sum(arr, axis=1)}")

[[0 1 2]
 [3 4 5]
 [6 7 8]]
sum of column: [ 9 12 15]
sum of row: [ 3 12 21]


3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [9]:
#please enter your code belowthis line.
import numpy as np

arr = np.arange(0,16).reshape(4,4)

print(f"mininmum value: {np.amin(arr)}")
print(f"mininmum value: {np.amax(arr)}")
print(f"mean value: {np.mean(arr)}")

mininmum value: 0
mininmum value: 15
mean value: 7.5


4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [23]:
#please enter your code below this line.
import numpy as np

arr = np.arange(0,100).reshape(10,10)
print(arr)

print(f"7th row: {arr[6,:]}\n")
print(f"4-8 row:{arr[3:7,:]}\n")
print(f"value at the index 5,5: {arr[5][5]}\n")
print(f"5th column: {arr[:,4]}\n")
print(f"column from 2-5: {arr[:,1:4]}")

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
7th row: [60 61 62 63 64 65 66 67 68 69]

4-8 row:[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]

value at the index 5,5: 55

5th column: [ 4 14 24 34 44 54 64 74 84 94]

column from 2-5: [[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]
 [51 52 53]
 [61 62 63]
 [71 72 73]
 [81 82 83]
 [91 92 93]]
