1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [3]:
import numpy as np

x = np.random.randint(100, size=(3,3))
print(x)

y = np.random.randint(100, size=(3,3))
print(y)

p = np.dot(x,y)
print(p)

[[59 70 15]
 [83 81 96]
 [32 76 35]]
[[45 22 35]
 [55 81 98]
 [89 27  4]]
[[ 7840  7373  8985]
 [16734 10979 11227]
 [ 8735  7805  8708]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [8]:
import numpy as np

a =  [55,25,15], [30,44,2], [11,45,77]
arr = np.array(a)
print(arr)

dot = np.linalg.det(arr)
print(int(dot))

[[55 25 15]
 [30 44  2]
 [11 45 77]]
137180
